-- Create an OFFENSE lookup table
CREATE TABLE OFFENSE AS
SELECT DISTINCT OFFENSE_CODE, OFFENSE_NAME, OFFENSE_PARENT_GROUP, OFFENSE_GROUP, CRIME_AGAINST_CATEGORY
FROM CRIME_STAGE
GROUP BY OFFENSE_CODE, OFFENSE_NAME, OFFENSE_PARENT_GROUP, OFFENSE_GROUP, CRIME_AGAINST_CATEGORY
ORDER BY 1 ASC;


-- Drop unnecessary offense columns to minimize data duplication
ALTER TABLE CRIME
DROP (OFFENSE_GROUP, CRIME_AGAINST_CATEGORY, OFFENSE_PARENT_GROUP, OFFENSE_NAME)


-- Create a DATES lookup table
CREATE TABLE DATES AS
SELECT 
    CAST(SUBSTR(DATES, 0, 10) AS DATE) "CALENDAR_DATE"
    ,CAST(SUBSTR(DATES, 7, 4) AS INT) "YEAR"
    ,CAST(SUBSTR(DATES, 0, 2) AS INT) "MONTH"
    ,CASE
        WHEN SUBSTR(DATES, 0, 2) = '01' THEN 'JANUARY'
        WHEN SUBSTR(DATES, 0, 2) = '02' THEN 'FEBRUARY'
        WHEN SUBSTR(DATES, 0, 2) = '03' THEN 'MARCH'
        WHEN SUBSTR(DATES, 0, 2) = '04' THEN 'APRIL'
        WHEN SUBSTR(DATES, 0, 2) = '05' THEN 'MAY'
        WHEN SUBSTR(DATES, 0, 2) = '06' THEN 'JUNE'
        WHEN SUBSTR(DATES, 0, 2) = '07' THEN 'JULY'
        WHEN SUBSTR(DATES, 0, 2) = '08' THEN 'AUGUST'
        WHEN SUBSTR(DATES, 0, 2) = '09' THEN 'SEPTEMBER'
        WHEN SUBSTR(DATES, 0, 2) = '10' THEN 'OCTOBER'
        WHEN SUBSTR(DATES, 0, 2) = '11' THEN 'NOVEMBER'
        WHEN SUBSTR(DATES, 0, 2) = '12' THEN 'DECEMBER'
            ELSE NULL END "MONTH_NAME"
    ,CAST(SUBSTR(DATES, 4, 2) AS INT) "DAY"
    ,TO_CHAR(CAST(SUBSTR(DATES, 0, 10) AS DATE), 'DAY') "DAY_NAME"
FROM (
    SELECT DISTINCT CAST(SUBSTR(OFFENSE_START_DATETIME, 0, 10) AS DATE) "DATES"
    FROM CRIME_STAGE
    WHERE OFFENSE_START_DATETIME IS NOT NULL
    UNION
    SELECT DISTINCT CAST(SUBSTR(OFFENSE_END_DATETIME, 0, 10) AS DATE) "DATES"
    FROM CRIME_STAGE
    WHERE OFFENSE_END_DATETIME IS NOT NULL
    UNION
    SELECT DISTINCT CAST(SUBSTR(REPORT_DATETIME, 0, 10) AS DATE) "DATES"
    FROM CRIME_STAGE
    WHERE REPORT_DATETIME IS NOT NULL
) DATES
ORDER BY 
    CAST(SUBSTR(DATES, 7, 4) AS INT) ASC
    ,CAST(SUBSTR(DATES, 0, 2) AS INT) ASC
    ,CAST(SUBSTR(DATES, 4, 2) AS INT) ASC


-- Create a TIMES lookup table
CREATE TABLE TIMES AS
SELECT 
    TIMES "TIME_OF_DAY"
    ,CAST(SUBSTR(TIMES, 0, 8) AS TIMESTAMP) "TIME_OF_DAY_AS_TIME"
    ,CAST(SUBSTR(TIMES, 0, 2) AS INT) "TIME_HOUR"
    ,CAST(SUBSTR(TIMES, 4, 2) AS INT) "TIME_MINUTE"
    ,CAST(SUBSTR(TIMES, 7, 2) AS INT) "TIME_SECOND"
    ,SUBSTR(TIMES, -2) "AM_OR_PM"
FROM (
    SELECT DISTINCT SUBSTR(OFFENSE_START_DATETIME, -11) "TIMES"
    FROM CRIME_STAGE
    WHERE OFFENSE_START_DATETIME IS NOT NULL
    UNION
    SELECT DISTINCT SUBSTR(OFFENSE_END_DATETIME, -11) "TIMES"
    FROM CRIME_STAGE
    WHERE OFFENSE_END_DATETIME IS NOT NULL
    UNION
    SELECT DISTINCT SUBSTR(REPORT_DATETIME, -11) "TIMES"
    FROM CRIME_STAGE
    WHERE REPORT_DATETIME IS NOT NULL
) TIMES
ORDER BY
    SUBSTR(TIMES, -2) ASC
    ,CAST(SUBSTR(TIMES, 0, 2) AS INT) ASC
    ,CAST(SUBSTR(TIMES, 4, 2) AS INT) ASC
    ,CAST(SUBSTR(TIMES, 7, 2) AS INT) ASC
    

-- Finalizes CRIME table
CREATE TABLE CRIME AS
SELECT
    REPORT_NUMBER
    ,OFFENSE_ID
    ,CAST(SUBSTR(OFFENSE_START_DATETIME, 0, 10) AS DATE) OFFENSE_START_DATE
    ,SUBSTR(OFFENSE_START_DATETIME, -11) OFFENSE_START_TIME_OF_DAY
    ,CAST(SUBSTR(OFFENSE_END_DATETIME, 0, 10) AS DATE) OFFENSE_END_DATE
    ,SUBSTR(OFFENSE_END_DATETIME, -11) OFFENSE_END_TIME_OF_DAY
    ,CAST(SUBSTR(REPORT_DATETIME, 0, 10) AS DATE) REPORT_DATE
    ,SUBSTR(REPORT_DATETIME, -11) REPORT_TIME_OF_DAY   
    ,OFFENSE_CODE
    ,ONE_HUNDRED_BLOCK_ADDRESS
    ,LONGITUDE
    ,LATITUDE
    ,PRECINCT
    ,SECTOR
    ,BEAT
    ,MCPP
FROM CRIME_STAGE

-- Grant necessary permissions
GRANT SELECT,INSERT,UPDATE,DELETE ON CRIME TO aausek;
GRANT SELECT,INSERT,UPDATE,DELETE ON OFFENSE TO aausek;
GRANT SELECT,INSERT,UPDATE,DELETE ON DATES TO aausek;
GRANT SELECT,INSERT,UPDATE,DELETE ON TIMES TO aausek;